version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_USER_DB}
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: gocrud-auth-api
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: ${MONGODB_URL}
      MONGODB_USER_DB: ${MONGODB_USER_DB}
      MONGODB_USER_COLLECTION: ${MONGODB_USER_COLLECTION}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      LOG_OUTPUT: ${LOG_OUTPUT}
      LOG_LEVEL: ${LOG_LEVEL}
    # Se quiser usar .env, descomente a linha abaixo
    # env_file:
    #   - .env
    restart: always

volumes:
  mongo_data: 